# Generated by Django 6.0.3 on 2026-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_caloria', models.CharField()),
                ('meta_proteinas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='refeicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('calorias', models.IntegerField(default=0)),
                ('proteinas', models.FloatField(default=0.0)),
                ('data', models.DateField()),
            ],
        ),
    ]
