# Generated by Django 6.0.3 on 2026-04-02 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='meta_caloria',
        ),
        migrations.AddField(
            model_name='metas',
            name='meta_calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metas',
            name='meta_proteinas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='refeicoes',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
